name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Pull Docker Image
      run: sudo docker pull hrushikeshvagga/cicd-pipeline:latest

    - name: Delete old Docker container
      run: docker rm -f cicd-pipeline-container || true

    - name: Run docker container
      run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container hrushikeshvagga/cicd-pipeline:latest
